modelIOConfig:
  configPath: ./config.yml                           # FilePath of this file
  cPProfilePath: ./data/cp_profile.txt               # FilePath to Profile txt of c_p
  RProfilePath: ./data/R_profile.txt                 # FilePath to Profile txt of R of the atmo
  betaAProfilePath: ./data/beta_a_profile.txt        # FilePath to Profile txt of beta_a of aerosol-mixed of the atmo
  initTProfilePath: ./data/init_T_profile.txt        # FilePath to Profile txt of Initial Temperature for the model
  outputPath: ./output                               # The output directory where the temperature(t, z) will be saved into.
modelStructureConfig:
  dz: 100                                            # the vertical cell gap length, in meter
  dt: 600                                            # the time gap in seconds
  nz: 21                                             # total vertical layer count
  nt: 360                                            # total timestep count
  