modelIOConfig:
  configPath: ./config.yml                            # FilePath of this file
  cPProfilePath: ../data/cp_profile.txt               # FilePath to Profile txt of c_p
  RProfilePath: ../data/R_profile.txt                 # FilePath to Profile txt of R of the atmo
  aSwProfilePath: ../data/a_sw_profile.txt            # FilePath to Profile txt of absorvity of shortwave (< 4 micrometer)
  aLwProfilePath: ../data/a_lw_profile.txt            # FilePath to Profile txt of absorvity of longwave (> 4 micrometer)
  initTProfilePath: ../data/init_T_profile.txt        # FilePath to Profile txt of Initial Temperature for the model
  densityProfilePath: ../data/density_profile.txt     # FilePath to Profile txt of Atmospheric Density Profile
  outputPath: ./output                               # The output directory where the temperature(t, z) will be saved into.
modelStructureConfig:
  dz: 1000                                            # the vertical cell gap length, in meter
  dt: 10                                              # the time gap in seconds
  dx: 1000                                            # the horizontal cell gap length, in longitudal-direction, in meter
  dy: 1000                                            # the horizontal cell gap length, in latitudual-direction, in meter
  nz: 21                                             # total vertical layer count
  nt: 10000                                          # total timestep count
  Csua: 2092000000000.                               # Heat Capacity of the Surface, per unit area. in J/K m^2
  